### ISSUE TITLE
Interburst vs interflash intervals

### ISSUE THREAD

**Issue by prrathi** [peleg-lab/EmergentPeriodicity#1]
Hi,
I enjoyed reading the paper and thank you for providing this repo to accompany it. In the `readme.md` under the Experimental Data section, the `envelope_01ff.csv` is described as representing the interflash interval, while the other files are described as the interburst data. However, in the paper, it seems the envelope is used for the interburst intervals- which I interpreted as $T_b$- and the other files are used for the interflash interval- which I interpreted to be $T_d$. Just wanted to clarify if this was a mistake or I got confused between the two, thanks!

**Comment by owingit** [comment]
T_d is the flash length! T_b is the interflash and interburst interval, since in the simulation we make them analogous.
